# Generated by Django 5.0.14 on 2026-07-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='raw_extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
