# Generated by Django 5.0.14 on 2026-07-09 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_prices', to='ledger.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='ledger.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'product')},
            },
        ),
    ]
