# Generated by Django 5.0.14 on 2026-07-09 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_vendorproductprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_diff_ratio', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('auto_resolved', 'Auto-resolved'), ('needs_approval', 'Needs approval'), ('unmatched', 'Unmatched')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_result', to='ledger.invoicelineitem')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.product')),
            ],
        ),
    ]
