# Generated by Django 5.0.14 on 2026-07-20 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_reconciliationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(choices=[('action_agent', 'Action agent'), ('owner', 'Owner')], max_length=30)),
                ('action_type', models.CharField(choices=[('restock', 'Restock'), ('reorder_suggested', 'Reorder suggested'), ('vendor_alert_drafted', 'Vendor alert drafted'), ('approved', 'Owner approved'), ('rejected', 'Owner rejected')], max_length=30)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.product')),
                ('reconciliation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='ledger.reconciliationresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
